#language: java
#jdk:
#-openjdk8
#script: mvn clean verify
#language: java
#jdk: 
#  -openjdk8
#sudo: false
#script: mvn clean verify
  
sudo: required
language: java
jdk: oraclejdk8

services:
  - postgres

before_install:
  - cd centersystem
  - chmod +x ./mvnw

script:
  - ./mvnw clean install -DskipTests=true -B
 

dist: trusty

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: centersystem